// collectors/gmgn/verifyAuth.js - standalone auth check.
// Run with: npm run gmgn:verify-auth
//
// Calls the lowest-cost authenticated GMGN endpoint (/v1/user/info)
// purely to prove GMGN_API_KEY works against the live GMGN OpenAPI.
// Stores nothing - this is authentication verification only.

const config = require("../../config/env");
const { createGmgnClient, GmgnAuthError } = require("./authClient");

async function main(){

    if(!config.GMGN_API_KEY){

        console.error(
            "GMGN authentication cannot be verified: GMGN_API_KEY is not set in server/.env.\n" +
            "Run `npm run gmgn:generate-keys` first, then register the printed public key at " +
            "https://gmgn.ai/ai to obtain an API key, and set GMGN_API_KEY in server/.env."
        );

        process.exit(1);

    }

    const client = createGmgnClient({

        apiKey: config.GMGN_API_KEY,

        privateKeyPem: config.GMGN_PRIVATE_KEY,

        host: config.GMGN_HOST

    });

    try{

        const { data } = await client.getUserInfo();

        console.log("GMGN authentication succeeded.");
        console.log(JSON.stringify(data, null, 2));

        process.exitCode = 0;

    }
    catch(err){

        if(err instanceof GmgnAuthError){

            console.error("GMGN authentication failed - stopping (not guessing).");
            console.error(err.message);

            if(err.status === 401 || err.apiError === "UNAUTHORIZED"){

                console.error(
                    "This usually means GMGN_API_KEY is invalid, or the Ed25519 public key " +
                    "generated by `npm run gmgn:generate-keys` was never registered at " +
                    "https://gmgn.ai/ai."
                );

            }

        }
        else{

            console.error("GMGN authentication request failed - stopping (not guessing).");
            console.error(err.message);

        }

        process.exitCode = 1;

    }

}

main();
