// services/featureNormalizer.js - Decision Engine V2 sprint. The single,
// shared implementation of "turn a free-text AI reason string into a
// stable feature key" and "enumerate the feature co-occurrence
// combinations for a set of features" - used by BOTH the AI Performance
// Audit script (server/scripts/audit-ai-performance.js, which already
// had its own inline copy of the normalization regex before this file
// existed) and services/decisionEngineV2.js below. Extracted here so the
// live Decision Engine and the offline audit tool can never silently
// drift into two different definitions of "the same feature" - the
// audit's historical stats and the live engine's lookup key MUST be
// generated by the identical function, or Layer 3's historical lookup
// would be comparing apples to oranges.
//
// Pure functions only - no DB, no I/O, no trading-logic decisions here.

// Strips volatile per-token numeric detail (dollar amounts, percentages,
// parenthetical specifics, bare counts) from a reasons/riskReasons
// string so "Net accumulation detected ($1,332 net buys, 24h)" and
// "... ($3,025 ...)" tally/lookup as the SAME feature. Never invents a
// category name - only removes the parts that would otherwise make
// every occurrence unique.
function normalizeFeature(raw){
    return raw
        .replace(/\([^)]*\)/g, "")
        .replace(/\$[\d,]+(\.\d+)?/g, "")
        .replace(/\b\d+(\.\d+)?%/g, "")
        .replace(/\b\d+\b/g, "")
        .replace(/\s{2,}/g, " ")
        .trim();
}

// Normalizes and de-duplicates a raw reasons array (order-preserving is
// not needed - callers that care about a stable combination KEY re-sort
// alphabetically anyway, see comboKey below).
function normalizeFeatureList(rawReasons){
    if(!Array.isArray(rawReasons)) return [];
    return [...new Set(rawReasons.map(normalizeFeature).filter(Boolean))];
}

// A single, deterministic string key for a combination of normalized
// features - same convention services/scripts/audit-ai-performance.js's
// section4/4b already established ("Feature A + Feature B"), sorted so
// the same combination always produces the same key regardless of the
// order the underlying reasons array happened to list them in.
function comboKey(features){
    return features.slice().sort().join(" + ");
}

// Enumerates every combination of size 1..maxSize from a (already
// normalized, already deduplicated) feature list, largest-size-first
// within each token's own list (callers doing a "best evidenced match"
// lookup - see decisionEngineV2.js - want to try the most specific
// combination first). maxSize defaults to 3 (pair + triplet, matching
// the audit script's own Section B) - not unbounded, since a candidate
// with N features would otherwise produce 2^N combinations for no real
// benefit (this codebase's own audit only ever tracks up to triplets).
function getCombinationKeys(features, maxSize = 3){
    const keys = [];
    const n = features.length;
    const cappedSize = Math.min(maxSize, n);

    function combine(start, chosen){
        if(chosen.length > 0) keys.push(comboKey(chosen));
        if(chosen.length === cappedSize) return;
        for(let i = start; i < n; i++){
            combine(i + 1, [...chosen, features[i]]);
        }
    }

    // Build size 1..cappedSize combinations, then sort so the largest
    // combinations (most specific, most evidence-dense) come first.
    combine(0, []);
    return [...new Set(keys)].sort((a, b) => {
        const sizeA = a.split(" + ").length;
        const sizeB = b.split(" + ").length;
        return sizeB - sizeA;
    });
}

module.exports = { normalizeFeature, normalizeFeatureList, comboKey, getCombinationKeys };
